version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12.8
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=core
